version: "3.7"
services:
  web:
    image: nginx:alpine
    container_name: linux
    ports:
      - "8000:80"
    volumes:
      - ./app:/usr/share/nginx/html
  ubuntu:
    image: ciceroreis/ubuntu:20.04
    container_name: ubuntu
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - 22:22
    restart: on-failure
    command: bash -c "service ssh start && bash"
    stdin_open: true
    tty: true
